### PR TITLE
Composite build attempt

### PR DESCRIPTION
**Pull request by travis79**
This is an attempt to build as a composite.

The error I see here is:
```
➜  better-builds-prototype git:(main) ✗ ./gradlew build

> Configure project :android
WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
Compatible side by side NDK version was not found. Default is 20.0.5594570.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> Failed to notify project evaluation listener.
   > NDK is not installed
   > Task with name 'cargoBuild' not found in project ':android'.
   > Task with name 'cargoBuild' not found in project ':android'.
```

### CODE REVIEW

**Comment by rfk** [comment]
@travis79 when I try to run this locally, I get an error from `git submodule update --init`:

```
fatal: remote error: upload-pack: not our ref 8d11f0b247290e65e74affe92552bf5007c27ec4                                                                                                       Fetched in submodule path 'glean', but it did not contain 8d11f0b247290e65e74affe92552bf5007c27ec4. Direct fetching of that commit failed.
```

Any change you were using some local modifications to Glean that haven't been pushed, causing the above failing to init the submodule?

**Comment by rfk** [comment]
FWIW my instance is that composite builds are going to be the way to go here. IME they're pretty fiddly, but we don't need them to do very much and it seems likely to be less fiddly than getting all different projects to behave well when included directly into a single gradle build.

**Comment by travis79** [comment]
> @travis79 when I try to run this locally, I get an error from `git submodule update --init`:
> 
> ```
> fatal: remote error: upload-pack: not our ref 8d11f0b247290e65e74affe92552bf5007c27ec4                                                                                                       Fetched in submodule path 'glean', but it did not contain 8d11f0b247290e65e74affe92552bf5007c27ec4. Direct fetching of that commit failed.
> ```
> 
> Any chance you were using some local modifications to Glean that haven't been pushed, causing the above failing to init the submodule?

Hmm, Yeah, I applied the changes to add the library loading hooks from [this PR](https://github.com/mozilla/glean/pull/1290), tweaked to fit.  Let me see if I can give you a diff of my changes...

**Comment by travis79** [comment]
@rfk Here is a PR to my Glean fork with the changes: https://github.com/travis79/glean/pull/1

**Comment by travis79** [comment]
Okay, this builds with cargo and gradle, but I can't get it to work with the rust gradle plugin for some reason to build the rusty bits via gradle. I'm working on a doc that outlines what I have learned and will try and answer some of the questions in the Better Builds proposal.

**Pull request merged**
